site_name: Data analysis in practice
nav:
    - Home: index.md
    - Precourse preparations: precourse.md
    - Course schedule: course_schedule.md
    - Day 1:
      - Data1-qPCR: day1/Data1.md
      - Theory: day1/knitr.md
      - Data2-Birthweight: day1/Data2.md
    - Day 2:
      - Data3-Birthweight again: day2/Data3.md
      - Data4-Simulations: day2/Data4.md
      - Data5-Hormone action: day2/Data5.md



theme:
  name: material
  logo: assets/images/SIB_logo.svg
  favicon: assets/images/SIB_logo.svg

# Repository
repo_name: sib-swiss/Data-analysis-in-practice
repo_url: https://github.com/sib-swiss/Data-analysis-in-practice

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
